Update poker.py
Small change to fix:

UnboundLocalError: local variable 'player_added' referenced before assignment (file "/home/web/CasinoBot/casino/poker.py", line 103, in ante)